AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        WEBHOOK_URL: '{{resolve:ssm:webhook_url:3}}'

Resources:
  StatusPage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: broadcast/
      Handler: app.status_page
      Runtime: nodejs12.x
      Events:
        StatusPage:
          Type: Api
          Properties:
            Path: '/statuspage'
            Method: post

  GitHub:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: broadcast/
      Handler: app.github
      Runtime: nodejs12.x
      Events:
        StatusPage:
          Type: Api
          Properties:
            Path: '/github'
            Method: post
